// Generates src/lib/build-info.ts with the current build's tag, short commit
// id, and build timestamp. Run automatically before `vite build` and `vite dev`
// (npm prebuild / predev hooks). Output is gitignored.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'src', 'lib', 'build-info.ts');

function git(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const tag = git('git describe --tags --abbrev=0') || 'dev';
const commit = git('git rev-parse --short=10 HEAD') || 'unknown';
const date = new Date().toISOString();

const content = `// GENERATED by scripts/version.mjs — do not edit by hand.
export interface BuildInfo {
  tag: string;
  commit: string;
  date: string;
}

export const buildInfo: BuildInfo = {
  tag: ${JSON.stringify(tag)},
  commit: ${JSON.stringify(commit)},
  date: ${JSON.stringify(date)},
};
`;

writeFileSync(outFile, content);
console.log(`build-info: tag=${tag} commit=${commit} date=${date}`);