// Generates src/lib/build-info.ts with the current build's tag, short commit
// id, and build timestamp. Run automatically before `vite build` and `vite dev`
// (npm prebuild / predev hooks). Output is gitignored.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'src', 'lib', 'build-info.ts');

function git(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

// Prefer values injected via env (the Docker build passes GIT_TAG /
// GIT_COMMIT / BUILD_DATE as build args, since .git isn't in the image).
// Otherwise read them from a git checkout (local dev).
function envOr(envName, compute) {
  const value = (process.env[envName] || '').trim();
  if (value) return value;
  return compute();
}

const tag = envOr('GIT_TAG', () => git('git describe --tags --abbrev=0')) || 'dev';
const commit = envOr('GIT_COMMIT', () => git('git rev-parse --short=10 HEAD')) || 'unknown';
const date = envOr('BUILD_DATE', () => new Date().toISOString());

const content = `// GENERATED by scripts/version.mjs — do not edit by hand.
export interface BuildInfo {
  tag: string;
  commit: string;
  date: string;
}

export const buildInfo: BuildInfo = {
  tag: ${JSON.stringify(tag)},
  commit: ${JSON.stringify(commit)},
  date: ${JSON.stringify(date)},
};
`;

writeFileSync(outFile, content);
console.log(`build-info: tag=${tag} commit=${commit} date=${date}`);